// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoneyHub.Infrastructure;

#nullable disable

namespace PoneyHub.Infrastructure.Migrations
{
    [DbContext(typeof(PoneyHubDbContext))]
    [Migration("20250824223552_AddPoneysDonnees")]
    partial class AddPoneysDonnees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoneyHub.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Libelle = "Terrestre"
                        },
                        new
                        {
                            Id = 2,
                            Libelle = "Licorne"
                        },
                        new
                        {
                            Id = 3,
                            Libelle = "Pégase"
                        });
                });

            modelBuilder.Entity("PoneyHub.Domain.Entities.Poney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int");

                    b.Property<double>("Coefficient")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Poney", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 3,
                            Coefficient = 1.0,
                            Description = "Aime quand y'a plein de couleur de partout",
                            Nom = "Karim",
                            Photo = ""
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 1,
                            Coefficient = 1.0,
                            Description = "Aime se poser dans l'herbe, la brouter et prendre son temps",
                            Nom = "Matthieu",
                            Photo = ""
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 1,
                            Coefficient = 1.0,
                            Description = "Préfère rester dans son coin mais prend des coups de folie par moment",
                            Nom = "Valentin",
                            Photo = ""
                        },
                        new
                        {
                            Id = 4,
                            CategorieId = 2,
                            Coefficient = 25.0,
                            Description = "Adore quand ca danse et que ca se frotte",
                            Nom = "Fabrice",
                            Photo = ""
                        },
                        new
                        {
                            Id = 5,
                            CategorieId = 1,
                            Coefficient = 1.0,
                            Description = "Deteste quand ça parle trop et préfere se focus sur l'action",
                            Nom = "Sylvain",
                            Photo = ""
                        },
                        new
                        {
                            Id = 6,
                            CategorieId = 1,
                            Coefficient = 1.0,
                            Description = "Vieux poney qui a ses petites habitudes mais très gentil",
                            Nom = "Elric",
                            Photo = ""
                        },
                        new
                        {
                            Id = 7,
                            CategorieId = 1,
                            Coefficient = 1.0,
                            Description = "Petit poney qui adore l'argent, et est parfait pour aller récolter les impots",
                            Nom = "Kevin",
                            Photo = ""
                        });
                });

            modelBuilder.Entity("PoneyHub.Domain.Entities.Prestation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateHeureDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateHeureFin")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantFacture")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PoneyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoneyId");

                    b.ToTable("Prestation", (string)null);
                });

            modelBuilder.Entity("PoneyHub.Domain.Entities.Poney", b =>
                {
                    b.HasOne("PoneyHub.Domain.Entities.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("PoneyHub.Domain.Entities.Prestation", b =>
                {
                    b.HasOne("PoneyHub.Domain.Entities.Poney", "Poney")
                        .WithMany("Prestations")
                        .HasForeignKey("PoneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poney");
                });

            modelBuilder.Entity("PoneyHub.Domain.Entities.Poney", b =>
                {
                    b.Navigation("Prestations");
                });
#pragma warning restore 612, 618
        }
    }
}
